feat: Support ModelMetadata endpoint
kserve/rest-proxy pull request #26
Opened 2023-08-25 18:33 UTC by rafvasq

Resolves #14

2023-08-29 22:13 UTC, Jooho commented
simply tested this and I confirm that this work well

1. Without version
~~~
 curl -k https://example-onnx-mnist-modelmesh-serving.apps.jlee-test.oylv.p1.openshiftapps.com/v2/models/example-onnx-mnist
{"name":"example-onnx-mnist__isvc-b29c3d91f3", "versions":["1"], "platform":"OpenVINO", "inputs":[{"name":"Input3", "datatype":"FP32", "shape":["1", "1", "28", "28"]}], "outputs":[{"name":"Plus214_Output_0", "datatype":"FP32", "shape":["1", "10"]}]}  support-rest-endpoints  ~/temp/20230822_Test_repo/rest-proxy       
~~~

2. With version
~~~
curl -k https://example-onnx-mnist-modelmesh-serving.apps.jlee-test.oylv.p1.openshiftapps.com/v2/models/example-onnx-mnist/versions/1
{"name":"example-onnx-mnist__isvc-b29c3d91f3", "versions":["1"], "platform":"OpenVINO", "inputs":[{"name":"Input3", "datatype":"FP32", "shape":["1", "1", "28", "28"]}], "outputs":[{"name":"Plus214_Output_0", "datatype":"FP32", "shape":["1", "10"]}]}
~~~

2023-09-26 19:29 UTC, ckadner requested changes
Thanks @rafvasq -- need a few updates for the go.mod dependencies. I get different generated results, without these updates

2023-09-26 19:29 UTC, ckadner commented on go.mod
> +	google.golang.org/genproto/googleapis/api v0.0.0-20230822172742-b8732ec3820d // indirect
these additional dependencies should not be required

2023-09-26 19:29 UTC, ckadner commented on go.mod
> +	google.golang.org/grpc v1.57.0
should we update those to the versions used by KServe?

2023-09-26 19:40 UTC, ckadner commented
Thanks @rafvasq -- did you also regenerate the protos?

With `google.golang.org/grpc v1.51.0` I do get slightly different generated code

https://github.com/kserve/rest-proxy/pull/26/files#diff-2858165aafcdd2fe79ab516a84060fb8645cd00e44a92f623f3a57fe4b3b569cR446


<img width="1068" alt="image" src="https://github.com/kserve/rest-proxy/assets/12246093/7486642b-d319-4471-9bb2-c68f716d5606">

2023-09-26 21:40 UTC, ckadner approved these changes
/lgtm

2023-09-26 21:46 UTC, merged