chore: Add code generation to Makefile
kserve/rest-proxy pull request #27
Opened 2023-09-28 01:21 UTC by ckadner

* Pre-install grpc-gateway plugin in developer Docker image
* Add `generate` make target to run protoc and automatically download required .proto files
* Add developer instructions to README.md

2023-09-28 17:54 UTC, ckadner commented
@rafvasq -- when you get a chance, could you try the revised developer setup and instructions?

`make generate` or `make run generate` should work on a fresh clone and/or after deleting your previously downloaded `google/api/*.proto` files.

2023-09-28 19:27 UTC, rafvasq requested changes
Thanks @ckadner. The developer setup/instructions look good aside from the small typo below and both `make generate` and `make run generate` on a fresh clone worked for me.

2023-09-28 19:59 UTC, ckadner commented on README.md
> +To update a running deployment of ModelMesh serving, add or update the `restProxy.image` section in the `model-serving-config` `ConfigMap` as described the [Modelmesh Serving configuration instructio
Good nit 🧶

2023-09-28 20:25 UTC, rafvasq approved these changes
/lgtm

2023-09-28 20:28 UTC, rafvasq approved these changes

2023-09-28 20:33 UTC, merged

2023-11-28 21:47 UTC, ckadner commented
/reopen